supported_comics = {
    "xkcd": {
        "name": "xkcd",
        "start_url": "https://xkcd.com/1/",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//a[@rel='next']/@href",
    },
    "xkcd_alt": {
        "name": "xkcd_alt",
        "start_url": "https://xkcd.com/1/",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//a[@rel='next']/@href",
        "alt_text": "//div[@id='comic']//img/@title",
    },
    "AtomicRobo": {
        "name": "AtomicRobo",
        "start_url": "https://www.atomic-robo.com/atomicrobo/v1ch1-cover",
        "comic_image_selector": "//div[@id='cc-comicbody']//img/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "Nedroid": {
        "name": "Nedroid",
        "start_url": "https://nedroid.com/?1",
        "comic_image_selector": "//img[@class='comic_img']/@src",
        "next_page_selector": "//a[text()='NEXT>']/@href",
    },
    "JL8": {
        "name": "JL8",
        "start_url": "https://limbero.org/jl8/1",
        "comic_image_selector": "//img[@alt='Comic']/@src",
        "next_page_selector": "//a[text()='>']/@href",
    },
    "SMBC": {
        "name": "SMBC",
        "start_url": "https://www.smbc-comics.com/comic/2002-09-05",
        "comic_image_selector": "//img[@id='cc-comic']/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "Blindsprings": {
        "name": "Blindsprings",
        "start_url": "https://www.blindsprings.com/comic/blindsprings-cover-book-one",
        "comic_image_selector": "//img[@id='cc-comic']/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "TheAbominableCharlesChristopher": {
        "name": "TheAbominableCharlesChristopher",
        "start_url": "https://karlkerschl.com/comic/episode-one/",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//a[contains(@class, 'comic-nav-next')]/@href",
    },
    "GuildedAge": {
        "name": "GuildedAge",
        "start_url": "http://guildedage.net/comic/chapter-1-cover/",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//a[contains(@class, 'comic-nav-next')]/@href",
    },
    "TalesOfElysium": {
        "name": "TalesOfElysium",
        "start_url": "https://ssp-comics.com/comics/toe/?page=1&mode=10",
        "comic_image_selector": "//div[@id='ImageComicContainer']//img[contains(@src, 'comic')]/@src",
        "next_page_selector": "//a[button/@id='next10Button']/@href",
    },
    "Gunshow": {
        "name": "Gunshow",
        "start_url": "https://gunshowcomic.com/1",
        "comic_image_selector": "//img[@class='strip']/@src",
        "next_page_selector": "//span[@class='snavb'][4]/a/@href",
    },
    "Lackadaisy": {
        "name": "Lackadaisy",
        "start_url": "https://www.lackadaisycats.com/comic.php?comicid=1",
        "comic_image_selector": "//div[@id='exhibit']/img/@src",
        "next_page_selector": "//div[@class='next']/a/@href",
    },
    "WildeLife": {
        "name": "WildeLife",
        "start_url": "https://www.wildelifecomic.com/comic/1",
        "comic_image_selector": "//img[@id='cc-comic']/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "ElGoonishShive": {
        "name": "ElGoonishShive",
        "start_url": "https://www.egscomics.com/comic/2002-01-21",
        "comic_image_selector": "//div[@id='cc-comicbody']//img/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "StandStillStaySilent": {
        "name": "StandStillStaySilent",
        "start_url": "https://www.sssscomic.com/comic.php?page=1",
        "comic_image_selector": "//img[@class='comicnormal' and contains(@src, 'comicpages')]/@src",
        "next_page_selector": "//a[img[contains(@src, 'next')]]/@href",
    },
    "SchlockMercenary": {
        "name": "SchlockMercenary",
        "start_url": "https://www.schlockmercenary.com/2000-06-12",
        "comic_image_selector": "//div[@class='strip-images']//img/@src",
        "next_page_selector": "//a[@class='next-strip']/@href",
    },
    "Nerfnow": {
        "name": "Nerfnow",
        "start_url": "https://www.nerfnow.com/comic/4",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//li[@id='nav_next']//a/@href",
    },
    "EdisonRex": {
        "name": "EdisonRex",
        "start_url": "https://www.edisonrex.net/comic/issue-1-cover",
        "comic_image_selector": "//div[@id='cc-comicbody']//img/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "Spinnerette": {
        "name": "Spinnerette",
        "start_url": "https://www.spinnyverse.com/comic/02-09-2010",
        "comic_image_selector": "//div[@id='cc-comicbody']//img/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "RyanMadeMistakes": {
        "name": "RyanMadeMistakes",
        "start_url": "https://ryanestrada.com/2024/Ryan%20Made%20Mistakes/index.html",
        "comic_image_selector": "//p/img/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
        "single_page": True,
    },
    "StarTrip": {
        "name": "StarTrip",
        "start_url": "https://www.startripcomic.com/comic/chapter-1-cover",
        "comic_image_selector": "//img[@id='cc-comic']/@src",
        "next_page_selector": "//a[@class='cc-next']/@href",
    },
    "GunnerkriggCourt": {
        "name": "GunnerkriggCourt",
        "start_url": "https://www.gunnerkrigg.com/?p=1",
        "comic_image_selector": "//img[@class='comic_image']/@src",
        "next_page_selector": "//a[img[contains(@src, 'next')]]/@href",
    },
    "Housepets": {
        "name": "Housepets",
        "start_url": "https://www.housepetscomic.com/comic/2008/06/02/when-boredom-strikes/",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//div[@id='comic']//@href",
    },
    "Aurora": {
        "name": "Aurora",
        "start_url": "https://comicaurora.com/aurora/0-1-1/",
        "comic_image_selector": "//div[contains(@class, 'webcomic-media')]//img/@src",
        "next_page_selector": "//a[contains(@class, 'next-webcomic-link')]/@href",
    },
    "TwoKinds": {
        "name": "TwoKinds",
        "start_url": "https://twokinds.keenspot.com/comic/1/",
        "comic_image_selector": "//article[contains(@class, 'comic')]//img/@src",
        "next_page_selector": "//a[contains(@class, 'navarrow navnext')]//@href",
    },
    "Freefall": {
        "name": "Freefall",
        "start_url": "http://freefall.purrsia.com/ff100/fv00001.htm",
        "comic_image_selector": "(//body//img/@src)[1]",
        "next_page_selector": "//a[text()='Next']//@href",
    },
    "SlightlyDamned": {
        "name": "SlightlyDamned",
        "start_url": "https://www.sdamned.com/comic/prologue",
        "comic_image_selector": "//div[@id='cc-comicbody']//img/@src",
        "next_page_selector": "//div[@id='cc-comicbody']//a/@href",
    },
    "LasLindas": {
        "name": "LasLindas",
        "start_url": "https://laslindas.kemono.cafe/comic/ll0001/",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//div[@id='comic']//a/@href",
    },
    "Rain": {
        "name": "Rain",
        "start_url": "https://rain.thecomicseries.com/comics/1/#content-start",
        "comic_image_selector": "//div[@id='comicimagewrap']//img/@src",
        "next_page_selector": "//a[contains(@rel, 'next')]//@href",
    },
    "MyImpossibleSoulmate": {
        "name": "MyImpossibleSoulmate",
        "start_url": "https://mis.thecomicseries.com/comics/2/#content-start",
        "comic_image_selector": "//div[@id='comicimagewrap']//img/@src",
        "next_page_selector": "//a[contains(@rel, 'next')]//@href",
    },
    "ArtificialIncident": {
        "name": "ArtificialIncident",
        "start_url": "https://www.artificialincident.com/comic/issue-one-life-changing/",
        "comic_image_selector": "(//div[@class='webcomic-image']//img/@src)[1]",
        "next_page_selector": "//div[@class='webcomic-image']//a/@href",
    },
    "Yosh": {
        "name": "Yosh",
        "start_url": "https://www.yoshsaga.com/comic/introduction/",
        "comic_image_selector": "(//div[@class='webcomic-image']//img/@src)[1]",
        "next_page_selector": "//div[@class='webcomic-image']//a/@href",
    },
    "StationV3": {
        "name": "StationV3",
        "start_url": "https://www.stationv3.com/d3/20170101.html",
        "comic_image_selector": "((//div[@id='middle']//center)[1]//img/@src)[5]",
        "next_page_selector": "(//div[@id='middle']//center)[2]//a[img[contains(@src, 'http://www.stationv3.com/images/next2.gif')]]/@href",
    },
    "SabrinaOnline": {
        "name": "SabrinaOnline",
        "start_url": "https://www.sabrina-online.com/1996-01.html",
        "comic_image_selector": "//h3//img[contains(@src, 'SO')]/@src",
        "next_page_selector": "(//a[img[contains(@alt, 'NEXT')]]/@href)[last()]",
    },
    "TheSwordInterval": {
        "name": "TheSwordInterval",
        "start_url": "https://swordinterval.thecomicseries.com/comics/1/#content-start",
        "comic_image_selector": "//img[@id='comicimage']/@src",
        "next_page_selector": "//a[contains(@rel, 'next')]//@href",
    },
    "QuestionableContent": {
        "name": "QuestionableContent",
        "start_url": "https://questionablecontent.net/view.php?comic=1",
        "comic_image_selector": "//img[@id='strip']/@src",
        "next_page_selector": "//a[contains(text(), 'Next')]//@href",
    },
    "VGCats": {
        "name": "VGCats",
        "start_url": "https://www.vgcats.com/comics/?strip_id=0",
        "comic_image_selector": "(//table//img[contains(@src, 'images')]/@src)[1]",
        "next_page_selector": "//table//a[img[contains(@src, 'next')]]/@href",
    },
    "SuperEffective": {
        "name": "SuperEffective",
        "start_url": "https://vgcats.com/super/index.php?strip_id=0",
        "comic_image_selector": "(//table//img[contains(@src, 'images')]/@src)[1]",
        "next_page_selector": "//table//a[img[contains(@src, 'next')]]/@href",
    },
    "RivalQuickies": {
        "name": "RivalQuickies",
        "start_url": "https://vgcats.com/rivals/?strip_id=0",
        "comic_image_selector": "(//table//img[contains(@src, 'images')]/@src)[1]",
        "next_page_selector": "//table//a[img[contains(@src, 'next')]]/@href",
    },
    "VisionHaze": {
        "name": "VisionHaze",
        "start_url": "https://www.visionhaze.com/index.php?p=1",
        "comic_image_selector": "//div[@class='page']//img/@src",
        "next_page_selector": "//div[@class='navbutton']//a[contains(text(), '›')]/@href",
    },
    "TheJunkHyenasDiner": {
        "name": "TheJunkHyenasDiner",
        "start_url": "https://junkhyenasdiner.com/comic/intro/",
        "comic_image_selector": "//div[@id='comic']//img/@src",
        "next_page_selector": "//a[@class='navi comic-nav-next navi-next']/@href",
    },
    "JackRabbit": {
        "name": "JackRabbit",
        "start_url": "https://jackrabbit.thecomicseries.com/comics/1/#content-start",
        "comic_image_selector": "//img[@id='comicimage']/@src",
        "next_page_selector": "//a[@rel='next']//@href",
    },
}
